# Generated by Django 4.0.1 on 2022-01-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escritores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autores', models.CharField(max_length=50)),
                ('libros', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Escritor',
                'verbose_name_plural': 'Escritores',
                'db_table': 'Escritor',
                'ordering': ['id'],
            },
        ),
    ]
